jsitaraman/tioga

src/utils.c

Fixing memory allocation to avoid inavlid write on variable cft in function uniquenodes()

memory allocation bugfix in uniquenodes()

---

src/ADT.C
src/CartBlock.C
src/CartBlock.h
src/CartGrid.C
src/MeshBlock.C
src/MeshBlock.h
src/bookKeeping.C
src/buildADTrecursion.c
src/cartOps.C
src/codetypes.h
src/exchangeAMRDonors.C
src/exchangeBoxes.C
src/exchangeDonors.C
src/exchangeSearchData.C
src/getCartReceptors.C
src/highOrder.C
src/holeMap.C
src/linklist.c
src/math.c
src/parallelComm.C
src/search.C
src/tioga.C
src/tiogaInterface.C
src/utils.c
src/writeOutput.C

Replace all macros (Min/Max, MIN/MAX, and free) with TIOGA_ prefixed
versions to avoid conflicts with builtins as well as other codes.

Replace macros with TIOGA_ prefix to avoid conflicts

---

src/MeshBlock.h

Following the resent addition of MACROS, this ensures that `interpList` is actually set to `NULL`.

Change free to TIOGA_FREE in resetInterpData().

---

src/dataUpdate.C
src/tioga.C
src/tioga.h

`cellGID` is a `uint64_t` datatype that was being truncated to a 4-byte in
in the `MeshBlock::getReceptorInfo` method, this was fine for small meshes
but does not work for meshes greater than 2.4B elements. This commit
fixes this by handling the 64-bit data across 2 4-byte integer entries
within the int data structures.

Fix handling of cellGID field in MeshBlock for large meshes

---

CMakeLists.txt
cmake/TIOGAConfig.cmake.in
src/MeshBlock.C
src/MeshBlock.h
src/exchangeBoxes.C
src/exchangeSearchData.C
src/search.C
src/tioga.C
src/tioga.h

This pull request adds a few modifications to fix scaling issues observed on 16k/32k MPI ranks on NERSC Cori system
- Use `MPI_AllReduce` to exchange boxes instead of send/recv of a large number of boxes
- Add option to determine _unique nodes_ using global node ID instead of coincident coordinate search. Can be disabled using the CMake option `-DTIOGA_HAS_NODEGID=OFF`

Fixes to scaling issues with Nalu-Wind

---

src/highOrder.C

Redo logic for `iblank_cell`
- Set to `1` if all the nodes are _field points_
- Set to `-1` if all the nodes are _fringe points_
- Set to `0` if any node is a _hole point_
Reverting back to the original behavior since we no longer use `iblank_cell` in [nalu-wind](https://github.com/exawind/nalu-wind/) to handle `inactive part`. The original behavior will minimize the amount of _gaps_ seen in viz with paraview.

Revert to old behavior for iblank_cell

---

case/run.sh

- Do not allow running when number of MPI ranks is not specified
- Use explanatory var names
- Change build4 dir usage back to build to be consistent with
instructions

Update run.sh script

---

src/exchangeAMRDonors.C

This pull request fixes the counter length (currently resulting in a bad access error) based on how `intcount` is incremented in the immediately preceding lines.

fixing counter length

---

src/CMakeLists.txt
src/CartBlock.C
src/CartBlock.h
src/CartGrid.h
src/linCartInterp.C
src/linCartInterp.h

This pull request introduces linear interpolation for the background Cartesian mesh where the solution is cell-centered. The linear interpolation is used by default if `(donor_frac == nullptr) && (pdegree == 0)`. The interpolation is modeled after a FE brick element where the nodes are neighboring cell centers.

introduce linear interpolation for cell-centered background mesh

---

src/CartBlock.h
src/tioga.C
src/tioga.h
src/tiogaInterface.C

This pull request creates an accessor function to register the solution for cartesian meshes. A boolean `isnodal` is introduced to keep track of whether the solution array corresponds to solution living on node or cell centers.

create accessor function to register solution for cartesian meshes

---

src/CartBlock.C
src/MeshBlock.C
src/linCartInterp.C

Addressing #18, this pull request includes the missing headers for `std::runtime_error` to resolve compile issues with certain compilers.

Adding #include <stdexcept> to resolve compile time errors

---

src/CartBlock.C
src/MeshBlock.C
src/linCartInterp.C

Cherry-picked the commit from the `master` branch to include the headers and merged it with the exawind branch to prevent breaking of code on certain compilers.

Adding #include <stdexcept> to resolve compile time errors 

---

src/CartBlock.C
src/CartBlock.h

This pull request renames the solution array for the background mesh from `q` to `qcell`, and introduces `qnode` as a nodal solution array for the background mesh. This is in accordance with the tasks listed below - 
https://github.com/jsitaraman/tioga/blob/2b215e11d0cd00bd9b7e3e45efd7bd5184fefeb4/TODO#L36
@jsitaraman  To avoid confusion with the `qnode` that is DG-related, may be it would be better to merge this pull request after the below task has been completed ? 
https://github.com/jsitaraman/tioga/blob/2b215e11d0cd00bd9b7e3e45efd7bd5184fefeb4/TODO#L21

TODO point 2

---

src/CMakeLists.txt
src/CartBlock.C
src/getCartReceptors.C
src/get_amr_index_xyz.c
src/test_amr_functions.c

Reverts jsitaraman/tioga#25
This commit breaks AMR connectivity when `nf > 0`

Revert "Complete removal of get_amr_index_xyz and left-over porder-related variables"

---

src/CartBlock.C
src/CartBlock.h
src/MeshBlock.h
src/cartUtils.h
src/getCartReceptors.C

This pull request introduces nodes as receptors on background mesh. The function `getCartReceptors` is changed to accommodate nodal receptors in the same data arrays following the cell receptors. Furthermore, certain member variables have been introduced in `CartBlock` to include node and cell numbers. Finally, a couple of checks have been added to make sure the current code works as it is with only cell solution since nodal solution (on background meshes) is not setup to be dealt with in the rest of the code.

Adding code to introduce nodes for background mesh

---

src/CartBlock.C
src/CartBlock.h
src/tioga.C
src/tioga.h
src/tiogaInterface.C

Based on `iblank_cell` this pull request creates an `iblank` array for nodes. The logic is as follows - If all cells shared by node are field, the node is marked field. If any cell shared by the node is hole, the node is marked hole. Everything else is marked fringe. The interface is changed to accept node iblanks when registering every patch. 
I have also fixed a bug in the computation of `nnode` (not used anywhere currently) as part of this pull request.
Edit: Following the discussion in https://github.com/jsitaraman/tioga/pull/29#discussion_r435960201 
I have updated the pull request (687d927) to evaluate the node iblank based on the `donorList`. Certain variables have been renamed for more clarity. 
Below is the `iblank_cell` and and corresponding `iblank` (averaged to cells using …

Create iblank array for nodal variables on Cartesian mesh

---

src/CartBlock.C
src/cartUtils.h
src/getCartReceptors.C

Seeing as how the `iblank` array requires computation of the node index in a patch vs `getCartReceptors` which required node index of a patch concatenated to the cell indices, this pull request introduces an additional function allowing to distinguish between the two.

separate inline functions for concatenated and standard node index

---

src/tioga.C

Fixing the call to wall time computation to account for cases where different processors might span different near-body blocks. Also commenting out `writeData(nvar,0)` call so that we aren't dumping files by default during simulations.

fix wall time computation for amr grid in parallel

---

src/CartGrid.h

Sets a few non-initialized pointers to `nullptr`. This is in preparation for #35.

Initialize pointers

---

src/CartBlock.C
src/CartBlock.h
src/CartGrid.C
src/CartGrid.h
src/MeshBlock.C
src/MeshBlock.h
src/TiogaMeshInfo.h
src/tioga.C
src/tioga.h
src/tioga_nogpu.h

This PR introduces data structures for registering host/device data for MeshBlock and CartGrid/Block

Registering host/device data from applications

---

src/cartOps.C

This pull request adds tolerance to bound checking for convex meshblock weights. The tolerance is chosen to be consistent with similar bound checking of weights at - https://github.com/jsitaraman/tioga/blob/exawind/src/dataUpdate.C#L64 and https://github.com/jsitaraman/tioga/blob/exawind/src/highOrder.C#L482

Add tolerance to bound checking

---

CMakeLists.txt

Quotation marks were misplaced so any entry in CXXFLAGS would lead to a build failure.

Fix quotation for CXXFLAGS

---

src/CartGrid.C
src/CartGrid.h
src/tioga.C
src/tioga.h

Update CartGrid interface to support two objectives:
Ensure that there is a valid AMRMeshInfo object on host and device even when
using the legacy AMR mesh registration interface.
Introduce a new `tioga::preprocess_amr_data` that will ensure that a valid
CartGrid instance exists on all MPI ranks visible to TIOGA even if the AMR
solver is running on a subset of MPI processes.

Generalize AMR patch support in TIOGA

---

CMakeLists.txt
driver/gpu_test.C
src/CMakeLists.txt
src/gpu_global_functions.h
src/tioga_gpu.h
src/tioga_nogpu.h

Adds CMake option `-DTIOGA_FAKE_GPU=ON` to enable GPU code pathways on GPU
builds for debugging/testing.

Fake GPU pathways on CPU build

---

driver/CMakeLists.txt
gridGen/CMakeLists.txt

I tested with Spack by creating two patches and adding them to the tioga package.py file with "spack edit tioga".

Fixed issue 54 by moving MPI options to target_compile_options

---

src/MeshBlock.C
src/MeshBlock.h
src/dMeshBlock.C
src/dMeshBlock.h

This pull request revises upon #53 to not only remove the obsolete set data functions, but also removes m_info_device from MeshBlock. It is sufficient for only dMeshBlock to own m_info_device since all MB gpu kernels are launched in dMeshBlock.

remove now redundant device-related functionalities in MeshBlock and dMeshBlock
